<x-user.layouts.base>
    <x-user.parts.about.hero/>
    <x-user.parts.about.headlined-cards/>
    <x-user.parts.about.intro-section/>
    <x-user.parts.about.awards/>
    <x-user.parts.about.statistics-slider/>
    <x-user.parts.about.directors/>
    <x-user.parts.about.repertoire/>
</x-user.layouts.base>
